spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:~/h2/kstd"
    username: kstd
    password: kstd123
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
